model: 
  name: resnet50
  version: pytorch/vision:v0.10.0
  pretrained: True

loss:
  name: arcface
  params:
    num_dim: 512
    s: 30.0
    m: 0.50
    easy_margin: False 
    # cross entropy
    size_average:
    ignore_index: -100
    reduce:
    reduction: mean

init: 
  name: xavier_uniform
  params:
    # xavier_uniform
    gain: 1.0

optimizer:
  name: sgd
  params:
    # sgd
    lr: 1.0e-1
    momentum: 0.9
    weight_decay: 5.0e-4

train:
  dset_type: clf
  epoch: 30
  batch_size: 200
  num_workers: 0

    
